spring.application.name=portal

# Server Port (Render automatically sets the PORT variable)
server.port=${PORT:8080}

# MySQL Connection Settings (Fetches values from Render Environment Variables with local fallbacks)
# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.lxfcvtqduguimlgptksr.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Har353@*1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2408c692257d00f68d60d3d3a0c5c3c0a
jwt.expiration=36000000